### ISSUE TITLE
do not reactivate

### ISSUE THREAD

**Issue by thebigsmileXD** [ElywingReactive/ElywingReactive#7]
thats all, brb leaving this crap

**Comment by XxParkerGamesxX** [comment]
Yes Reactivate people loved this software

**Comment by XxParkerGamesxX** [comment]
We will make it great again!!!

**Comment by caspervanneck** [comment]
@thebigsmileXD sorry but it was a good software

**Comment by caspervanneck** [comment]
We take it over

**Comment by thebigsmileXD** [comment]
it was not. namespace issues, always outdated etc. i am waiting for the 8th imagicalmine reactivation please!

**Comment by XxParkerGamesxX** [comment]
@thebigsmileXD we will make this a great software our goal is to kill Tesseract

**Comment by thebigsmileXD** [comment]
oh, in this point i support you. but create a pmmp fork instead, and learn proper git. all these copy pasted updates are fails and mess

**Comment by caspervanneck** [comment]
https://github.com/ImagicalMine-Reactive @thebigsmileXD only am not going to update it

**Comment by caspervanneck** [comment]
I know to make a pmmp spoon or fork its better I know

**Comment by Fabiansigala** [comment]
Ok

**Comment by Fabiansigala** [comment]
And hello @thebigsmileXD

**Comment by thebigsmileXD** [comment]
and bye
